@baseUrl = http://localhost:3002
@ct = application/json
POST {{baseUrl}}/api/auth/register
Content-Type: {{ct}}

{
  "name" : "bereket",
  "email" : "b@gsmail.com",
  "password" : "123"
}

###
POST {{baseUrl}}/api/auth/login
Content-Type: {{ct}}

{
  "email" : "b@gsmail.com",
  "password" : "123"
}

###
GET {{baseUrl}}/api/health
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhOTk4NTc0MzFkZGEyNjEzYzM2NDU1OCIsImlhdCI6MTc4ODQ3MDc2MCwiZXhwIjoxNzg5MDc1NTYwfQ.KiDAACt-38mOb0yytJDmdaIxkGzE8WOoh-5rA-npkqo